---

name: Build the image and push it to ghcr.io

on:
  push:
    branches:
      - main
    paths:
      - wolfi-node-buildah.yml
      - .github/workflows/build-and-publish-to-ghcr.yml
  workflow_dispatch:
  schedule:
    # run every Monday at 01:30
    - cron: '30 1 * * 1'

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-the-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # https://github.com/chainguard-images/actions/tree/main/apko-publish
      - name: Build image with Apko
        uses: chainguard-images/actions/apko-publish@03241d624cef245ada340d38c1ed42d44e2e15b0 # v1.0.33
        with:
          config: wolfi-node-buildah.yml
          tag: ghcr.io/kastl-ars/wolfi-node-buildah:latest ghcr.io/kastl-ars/wolfi-node-buildah:${{ github.sha }}

      # DISABLED due to the pinning for buildah 1.43
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      #   with:
      #     image-ref: ghcr.io/kastl-ars/wolfi-node-buildah:${{ github.sha }}
      #     format: 'table'
      #     exit-code: '1'
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'
