---

name: Build the image and push it to ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # run every Monday at 01:30
    - cron: '30 1 * * 1'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-the-image:
    runs-on: ubuntu-latest
    environment: melange
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      # https://github.com/chainguard-images/actions/tree/main/apko-publish
      - name: Build image with Apko
        uses: chainguard-images/actions/apko-publish@a63bd73b7ab5cb3ae175d81ab9b72e4922af3acd # v1.0.32
        with:
          config: wolfi-node-buildah.yml
          tag: ghcr.io/kastl-ars/wolfi-node-buildah:latest
